In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import string
from sklearn.preprocessing import StandardScaler
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from sklearn.metrics import roc_auc_score
from torch.optim import Adam, lr_scheduler
from sklearn.model_selection import train_test_split

In [2]:
def prep(series):
    for c in 'ABTCE':  
        series[c+'_count'] = series['f_27'].str.count(c)
    for i in range(10):
        series['pos'+str(i)] = series['f_27'].str.get(i).apply(ord) - ord('A')
    series['unique'] = series['f_27'].apply(lambda s:len(set(s)))
    series['i_02_21'] = (series.f_21 + series.f_02 > 5.2).astype(int) - (series.f_21 + series.f_02 < -5.3).astype(int)
    series['i_05_22'] = (series.f_22 + series.f_05 > 5.1).astype(int) - (series.f_22 + series.f_05 < -5.4).astype(int)
    i_00_01_26 = series.f_00 + series.f_01 + series.f_26
    series['i_00_01_26'] = (i_00_01_26 > 5.0).astype(int) - (i_00_01_26 < -5.0).astype(int)
    series['f_28'] = series['f_28']/100
    return series.drop(columns=['f_27'])

In [3]:
train_series = prep(pd.read_csv('train.csv'))
valid_series = prep(pd.read_csv('test.csv'))

In [4]:
X = train_series.drop(columns=['id','target']).values
y = train_series['target'].values
X_valid = valid_series.drop(columns=['id']).values

In [5]:
X_train, X_holdout, y_train, y_holdout = train_test_split(X, y, test_size=0.1, random_state=123)

In [6]:
XX = np.vstack((X_train,X_holdout,X_valid))

In [7]:
sc = StandardScaler()
sc.fit(XX)

StandardScaler()

In [8]:
sc.mean_, sc.scale_

(array([-1.99139759e-04,  3.35231009e-04,  4.91865108e-04, -4.61139352e-04,
         2.90640663e-05, -4.48457907e-05,  7.16404397e-04,  2.03117937e+00,
         2.05752750e+00,  2.36188875e+00,  2.17737500e+00,  1.80438312e+00,
         2.84253375e+00,  2.23923062e+00,  1.51513937e+00,  2.10080687e+00,
         2.09548500e+00,  1.85842750e+00,  2.06643625e+00,  3.08084317e-01,
        -1.76648401e-01, -1.55270565e-01, -7.67616258e-03, -3.70562894e-01,
        -3.41839023e-01,  1.75540783e-01,  3.57020587e-01,  5.01000667e-04,
         3.45848750e-01,  1.00284125e+00,  2.46214750e+00,  3.24328125e+00,
         4.34975000e-02,  1.47834812e+00,  5.97812500e-01,  4.98809375e-01,
         1.96664375e+00,  6.68870000e-01,  1.99077938e+00,  1.38585250e+00,
         4.67763125e-01,  2.37539938e+00,  9.36298312e+00,  2.02507750e+00,
         2.28332312e+00,  5.01429250e+00, -4.62937500e-03,  2.48875000e-03,
         1.68556250e-02]),
 array([0.99948944, 0.99829086, 1.00042761, 1.00086758, 0.999

In [9]:
X_train = sc.transform(X_train)
X_holdout = sc.transform(X_holdout)
X_valid = sc.transform(X_valid)

In [10]:
X_train[:2]

array([[ 0.06604802, -1.95217896,  2.34234642, -0.50997358, -0.19980724,
         0.55424035, -1.55428309,  0.58501675,  2.47753031,  0.38974266,
         1.10759162, -1.17315464, -1.04573086, -0.15556781, -0.37861093,
         0.57308   ,  2.50232099, -1.26593251, -0.6816248 , -1.03067016,
        -1.00835187,  0.94427169,  0.85987451,  0.31770311,  2.05069675,
         0.46456005, -0.52402869, -0.91150446,  1.37529538, -0.00346795,
        -1.08415031, -0.17087815, -0.21325003,  0.49031975,  1.90874495,
         1.00238409,  0.02224128,  0.70360417,  1.2586021 , -1.06741292,
         1.06669311,  1.5858311 , -1.29050608,  1.2326551 ,  1.6434655 ,
        -0.01602634,  0.0205493 , -0.01142337, -0.05907975],
       [-2.23754584,  1.02617583, -0.181566  , -0.46183511, -0.13567033,
         0.6929298 , -1.29213315, -0.01882749,  2.47753031, -0.83180815,
        -0.10778908, -0.52298527,  0.08937004, -1.45613551, -1.11357887,
         1.84773387,  0.57968451, -0.58474774,  0.59669784,  0.

In [11]:
np.std(X_train[:,0])

0.9994984181282446

In [12]:
class MyModel(nn.Module):
    def __init__(self, in_channels=49):
        super().__init__()
        self.fc1 = nn.Linear(in_channels, 64)
        self.bn1 = nn.BatchNorm1d(64)
        self.fc2 = nn.Linear(64, 64)
        self.bn2 = nn.BatchNorm1d(64)
        self.fc3 = nn.Linear(64,32)
        self.bn3 = nn.BatchNorm1d(32)
        self.fc4 = nn.Linear(32,1)
        self.dropout = nn.Dropout(p=0.02)
    
    def forward(self,X):
        X = self.bn1(F.relu(self.fc1(X)))
        X = self.dropout(X)
        X = self.bn2(F.relu(self.fc2(X)))
        X = self.dropout(X)
        X = self.bn3(F.relu(self.fc3(X)))
        X = self.dropout(X)
        X = self.fc4(X)
        X = torch.sigmoid(X).squeeze(dim=-1)
        return X

In [13]:
class MyDataset(Dataset):
    def __init__(self, X, y=None):
        self.X = X
        if y is None:
            self.y = None
        else:
            self.y = y
    
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        ''' input tensor shape is N*C '''
        X = self.X[idx]
        if self.y is None:
            y = -1
        else:
            y = self.y[idx]
        return (torch.tensor(X, dtype=torch.float32), torch.tensor(y, dtype=torch.float32))

In [61]:
def evaluate(model, test_loader):
    model.eval()
    with torch.no_grad():
        X, y = next(iter(test_loader))
        output = model(X)
        print(output[:10], y[:10])
        score = roc_auc_score(y.detach().numpy(), output.detach().numpy())
        loss = nn.BCELoss()(output, y)
    return score, loss

In [62]:
del model

In [63]:
0.98**200

0.0175879466057215

In [64]:
def train(Xdata, ydata, epoches=200, batch_size=1024):
    torch.manual_seed(1)
    for isplit, (train_idx, test_idx) in enumerate(kf.split(Xdata)):
        
        model = MyModel()
        
        X_train, y_train = Xdata[train_idx], ydata[train_idx]
        X_test, y_test = Xdata[test_idx], ydata[test_idx]
        train_dataset = MyDataset(X_train, y_train)
        test_dataset = MyDataset(X_test, y_test)
        train_loader = DataLoader(train_dataset, shuffle=True, drop_last=False, batch_size=batch_size)
        test_loader = DataLoader(test_dataset, shuffle=False, drop_last=False, batch_size=len(X_test))
    
        criteria = nn.BCELoss()
        optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
        lr_decay = lr_scheduler.ExponentialLR(optimizer, gamma=0.98)

        best_score = 0.0
        for epoch in range(epoches):

            curr_loss = 0.0
            model.train()

            for batch, (X, y) in enumerate(train_loader):
                output = model(X)            
                loss = criteria(output, y)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                curr_loss += loss.item() * len(y)

            curr_loss /= len(train_loader.dataset)
            score, test_loss = evaluate(model, test_loader)
            print(f"{epoch}: {curr_loss}; roc={score} test_loss={test_loss}")
            lr_decay.step()
            if (score > best_score):
                torch.save({'train_loss':curr_loss/len(train_loader.dataset),
                    'test_loss': test_loss,
                    'score': score,
                    'model': model.state_dict()},'nn_model_'+str(isplit)+'.pickle')

In [65]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)

In [57]:
X_train.shape, y_train.shape, X_holdout.shape, y_holdout.shape, X_valid.shape

((810000, 49), (810000,), (90000, 49), (90000,), (700000, 49))

In [66]:
train(X_train, y_train, batch_size=256*10, epoches=200)

tensor([0.9849, 0.3183, 0.0011, 0.9986, 0.2988, 0.9787, 0.9989, 0.7914, 0.9119,
        0.4402]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
0: 0.2414736752892718; roc=0.9860537404519322 test_loss=0.1509825736284256
tensor([9.7695e-01, 1.0298e-01, 2.2160e-04, 9.9733e-01, 1.5074e-01, 9.8812e-01,
        9.9943e-01, 9.7539e-01, 9.8597e-01, 5.3505e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
1: 0.14229276565122015; roc=0.9918313703309842 test_loss=0.12037302553653717
tensor([9.9877e-01, 1.5369e-01, 2.8201e-04, 9.9919e-01, 7.2781e-01, 9.9976e-01,
        9.9995e-01, 9.8754e-01, 9.9880e-01, 6.1525e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
2: 0.11978810336854723; roc=0.9930340349245599 test_loss=0.11056447774171829
tensor([9.9628e-01, 2.0098e-02, 4.5505e-04, 9.9953e-01, 2.0080e-01, 9.9980e-01,
        9.9974e-01, 9.3796e-01, 9.4645e-01, 5.9536e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
3: 0.10959612123760176; roc=0.9940295436413826 test_loss=0.11936135

tensor([9.9948e-01, 4.0310e-03, 4.3275e-07, 9.9950e-01, 3.8228e-01, 9.9999e-01,
        9.9998e-01, 9.9819e-01, 9.9988e-01, 9.6398e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
32: 0.0691382583865413; roc=0.9973638892218732 test_loss=0.06503008306026459
tensor([9.9982e-01, 1.6821e-03, 7.1773e-07, 9.9955e-01, 5.2179e-01, 9.9999e-01,
        9.9999e-01, 9.9911e-01, 9.9968e-01, 9.4895e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
33: 0.06917070907391148; roc=0.9972756410650498 test_loss=0.06611042469739914
tensor([9.9988e-01, 7.6493e-03, 7.9672e-07, 9.9927e-01, 2.2060e-01, 1.0000e+00,
        9.9999e-01, 9.9662e-01, 9.9938e-01, 9.7017e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
34: 0.0686960929117085; roc=0.9974223105094353 test_loss=0.06445206701755524
tensor([9.9987e-01, 4.5938e-03, 2.0264e-07, 9.9981e-01, 3.0854e-01, 9.9994e-01,
        1.0000e+00, 9.9912e-01, 9.9992e-01, 9.9364e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
35: 0.06884475665695873;

tensor([9.9998e-01, 1.7801e-03, 3.2660e-07, 9.9986e-01, 3.6011e-01, 1.0000e+00,
        1.0000e+00, 9.9943e-01, 9.9963e-01, 9.6387e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
64: 0.06297776126199299; roc=0.9976395998210159 test_loss=0.06138982996344566
tensor([9.9997e-01, 3.5032e-03, 3.4719e-07, 9.9988e-01, 4.0014e-01, 1.0000e+00,
        1.0000e+00, 9.9876e-01, 9.9906e-01, 9.8133e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
65: 0.06308538401568377; roc=0.9976365635432962 test_loss=0.0614449642598629
tensor([9.9999e-01, 5.4448e-03, 4.5507e-07, 9.9989e-01, 2.1160e-01, 1.0000e+00,
        1.0000e+00, 9.9893e-01, 9.9964e-01, 9.6550e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
66: 0.06299244400159812; roc=0.9976324109813942 test_loss=0.06148916110396385
tensor([9.9997e-01, 1.1287e-02, 1.7930e-07, 9.9994e-01, 3.5075e-01, 1.0000e+00,
        1.0000e+00, 9.9984e-01, 9.9982e-01, 9.8951e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
67: 0.06287299485486231

tensor([9.9998e-01, 1.7273e-03, 2.3891e-07, 9.9995e-01, 5.4104e-01, 1.0000e+00,
        1.0000e+00, 9.9899e-01, 9.9958e-01, 9.7341e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
96: 0.060499721073809964; roc=0.9976572689940277 test_loss=0.061910808086395264
tensor([9.9999e-01, 3.6566e-03, 9.9468e-08, 9.9997e-01, 3.3435e-01, 1.0000e+00,
        1.0000e+00, 9.9923e-01, 9.9970e-01, 9.6501e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
97: 0.0601497453984655; roc=0.9976649502648541 test_loss=0.061901066452264786
tensor([1.0000e+00, 1.9630e-03, 2.6172e-07, 9.9994e-01, 5.3445e-01, 1.0000e+00,
        1.0000e+00, 9.9953e-01, 9.9945e-01, 9.8626e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
98: 0.06031804435415032; roc=0.9976904171805709 test_loss=0.06099728122353554
tensor([1.0000e+00, 2.3286e-03, 7.3919e-08, 9.9997e-01, 4.4942e-01, 1.0000e+00,
        1.0000e+00, 9.9943e-01, 9.9973e-01, 9.7473e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
99: 0.06020815771670

tensor([1.0000e+00, 2.8198e-03, 7.6051e-08, 9.9997e-01, 5.0723e-01, 1.0000e+00,
        1.0000e+00, 9.9918e-01, 9.9975e-01, 9.8706e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
127: 0.058988071939459555; roc=0.997714087668201 test_loss=0.06097738817334175
tensor([1.0000e+00, 2.1937e-03, 1.1306e-07, 9.9996e-01, 6.5472e-01, 1.0000e+00,
        1.0000e+00, 9.9949e-01, 9.9976e-01, 9.8814e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
128: 0.05883639650580324; roc=0.9976978151661597 test_loss=0.06066720932722092
tensor([1.0000e+00, 3.2356e-03, 1.2303e-07, 9.9996e-01, 5.4892e-01, 1.0000e+00,
        1.0000e+00, 9.9911e-01, 9.9960e-01, 9.8672e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
129: 0.058699520804263924; roc=0.9976986462582298 test_loss=0.060833923518657684
tensor([1.0000e+00, 4.4144e-03, 1.2924e-07, 9.9996e-01, 6.2778e-01, 1.0000e+00,
        1.0000e+00, 9.9969e-01, 9.9983e-01, 9.8944e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
130: 0.0588913581

tensor([1.0000e+00, 3.3143e-03, 2.3560e-07, 9.9997e-01, 6.1606e-01, 1.0000e+00,
        1.0000e+00, 9.9960e-01, 9.9980e-01, 9.8811e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
158: 0.058013768019499604; roc=0.997691256586613 test_loss=0.0606958381831646
tensor([1.0000e+00, 4.6431e-03, 3.5487e-07, 9.9996e-01, 5.4297e-01, 1.0000e+00,
        1.0000e+00, 9.9947e-01, 9.9979e-01, 9.8844e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
159: 0.05815986587309543; roc=0.9976994362380913 test_loss=0.06063391640782356
tensor([1.0000e+00, 3.1035e-03, 2.2105e-07, 9.9998e-01, 5.4536e-01, 1.0000e+00,
        1.0000e+00, 9.9954e-01, 9.9974e-01, 9.9098e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
160: 0.058040320612030266; roc=0.9976976544547984 test_loss=0.06078438460826874
tensor([1.0000e+00, 3.4200e-03, 3.4187e-07, 9.9997e-01, 4.7951e-01, 1.0000e+00,
        1.0000e+00, 9.9941e-01, 9.9971e-01, 9.8997e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
161: 0.058497517138

tensor([1.0000e+00, 4.4776e-03, 3.2926e-07, 9.9996e-01, 6.6409e-01, 1.0000e+00,
        1.0000e+00, 9.9952e-01, 9.9982e-01, 9.8783e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
189: 0.05785579722604634; roc=0.9976857014042929 test_loss=0.06077937036752701
tensor([1.0000e+00, 3.5567e-03, 2.1098e-07, 9.9996e-01, 5.3976e-01, 1.0000e+00,
        1.0000e+00, 9.9944e-01, 9.9979e-01, 9.8745e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
190: 0.05774425791369544; roc=0.9976929047361588 test_loss=0.060786012560129166
tensor([1.0000e+00, 4.1070e-03, 2.9843e-07, 9.9996e-01, 5.6939e-01, 1.0000e+00,
        1.0000e+00, 9.9960e-01, 9.9983e-01, 9.8847e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
191: 0.058152702932740434; roc=0.9976920555669208 test_loss=0.060722820460796356
tensor([1.0000e+00, 5.0582e-03, 3.6024e-07, 9.9996e-01, 5.7414e-01, 1.0000e+00,
        1.0000e+00, 9.9960e-01, 9.9981e-01, 9.8678e-01]) tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1.])
192: 0.057770287

tensor([1.0000e+00, 9.9994e-01, 2.9108e-04, 4.0007e-03, 1.0000e+00, 3.7587e-04,
        9.9999e-01, 1.0000e+00, 2.1408e-03, 9.9993e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
21: 0.07446424468799874; roc=0.9968614719712475 test_loss=0.07546008378267288
tensor([1.0000e+00, 9.9976e-01, 3.3305e-04, 1.2340e-02, 9.9997e-01, 9.5314e-04,
        9.9991e-01, 1.0000e+00, 1.5521e-03, 9.9962e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
22: 0.07438960752737375; roc=0.996868111243579 test_loss=0.0710059404373169
tensor([1.0000e+00, 9.9995e-01, 7.0098e-05, 3.6281e-03, 1.0000e+00, 2.4706e-04,
        9.9998e-01, 1.0000e+00, 1.2216e-03, 9.9998e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
23: 0.07371187288820008; roc=0.9969546237803969 test_loss=0.07467266172170639
tensor([1.0000e+00, 9.9932e-01, 3.0556e-04, 2.3248e-03, 9.9999e-01, 6.0496e-04,
        9.9990e-01, 1.0000e+00, 5.9943e-04, 9.9974e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
24: 0.07354065896184356;

tensor([1.0000e+00, 9.9924e-01, 7.2386e-05, 1.1223e-03, 1.0000e+00, 5.4561e-04,
        9.9999e-01, 1.0000e+00, 4.5003e-04, 9.9994e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
53: 0.06596158295501897; roc=0.9973196599985722 test_loss=0.06679734587669373
tensor([1.0000e+00, 9.9983e-01, 4.3174e-05, 1.5154e-03, 1.0000e+00, 3.8697e-04,
        9.9999e-01, 1.0000e+00, 5.8747e-04, 9.9996e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
54: 0.06569569221617264; roc=0.9973003723435964 test_loss=0.06596003472805023
tensor([1.0000e+00, 9.9991e-01, 1.2480e-04, 1.5298e-03, 1.0000e+00, 3.4604e-04,
        1.0000e+00, 1.0000e+00, 6.4218e-04, 9.9997e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
55: 0.06532920665947008; roc=0.9972880638244697 test_loss=0.06605184078216553
tensor([1.0000e+00, 9.9971e-01, 1.6183e-04, 5.5658e-03, 9.9999e-01, 1.1847e-03,
        9.9999e-01, 1.0000e+00, 1.3756e-03, 9.9991e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
56: 0.0650901397841948

tensor([1.0000e+00, 9.9996e-01, 4.6935e-05, 1.8125e-03, 1.0000e+00, 5.6662e-04,
        1.0000e+00, 1.0000e+00, 4.0049e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
85: 0.06192428951922022; roc=0.9974513144477313 test_loss=0.06429199129343033
tensor([1.0000e+00, 9.9978e-01, 4.0729e-05, 2.0773e-03, 1.0000e+00, 8.6512e-04,
        1.0000e+00, 1.0000e+00, 6.9916e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
86: 0.062039062447018095; roc=0.9974080532609473 test_loss=0.06456413120031357
tensor([1.0000e+00, 9.9990e-01, 4.1395e-05, 4.0193e-03, 1.0000e+00, 1.3468e-03,
        1.0000e+00, 1.0000e+00, 4.5786e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
87: 0.06209455300260473; roc=0.9974343098337529 test_loss=0.06454811245203018
tensor([1.0000e+00, 9.9996e-01, 1.5019e-05, 7.8507e-04, 1.0000e+00, 4.7515e-04,
        1.0000e+00, 1.0000e+00, 5.3411e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
88: 0.061820325538700

tensor([1.0000e+00, 9.9991e-01, 4.6537e-05, 2.2931e-03, 1.0000e+00, 7.7640e-04,
        1.0000e+00, 1.0000e+00, 4.9269e-04, 9.9998e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
116: 0.06047644248347223; roc=0.9974677707200988 test_loss=0.06373514980077744
tensor([1.0000e+00, 9.9997e-01, 2.2598e-05, 2.2020e-03, 1.0000e+00, 5.0768e-04,
        1.0000e+00, 1.0000e+00, 2.8802e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
117: 0.06024829861006619; roc=0.9974698323198458 test_loss=0.06389135122299194
tensor([1.0000e+00, 9.9996e-01, 2.2988e-05, 1.8216e-03, 1.0000e+00, 6.8461e-04,
        1.0000e+00, 1.0000e+00, 6.6503e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
118: 0.06044384128517575; roc=0.9974506308317477 test_loss=0.06433270871639252
tensor([1.0000e+00, 9.9996e-01, 2.9910e-05, 1.5077e-03, 1.0000e+00, 1.1663e-03,
        1.0000e+00, 1.0000e+00, 4.2375e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
119: 0.060121282872

tensor([1.0000e+00, 9.9995e-01, 1.6112e-05, 1.5624e-03, 1.0000e+00, 4.8441e-04,
        1.0000e+00, 1.0000e+00, 1.5324e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
147: 0.05923913475172019; roc=0.9974691641833987 test_loss=0.06434856355190277
tensor([1.0000e+00, 9.9997e-01, 3.2839e-05, 1.7255e-03, 1.0000e+00, 8.8281e-04,
        1.0000e+00, 1.0000e+00, 3.5260e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
148: 0.059421514633261126; roc=0.997478123327349 test_loss=0.06361838430166245
tensor([1.0000e+00, 9.9997e-01, 2.0774e-05, 1.4815e-03, 1.0000e+00, 5.1664e-04,
        1.0000e+00, 1.0000e+00, 2.3766e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
149: 0.059141283138298695; roc=0.9974748768949028 test_loss=0.06403329968452454
tensor([1.0000e+00, 9.9996e-01, 4.0213e-05, 2.5482e-03, 1.0000e+00, 1.0191e-03,
        1.0000e+00, 1.0000e+00, 4.6494e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
150: 0.05937696797

tensor([1.0000e+00, 9.9994e-01, 3.8578e-05, 2.2271e-03, 1.0000e+00, 8.5299e-04,
        1.0000e+00, 1.0000e+00, 2.8143e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
178: 0.058731381624569125; roc=0.9974798959249117 test_loss=0.06354720145463943
tensor([1.0000e+00, 9.9996e-01, 3.3126e-05, 2.1404e-03, 1.0000e+00, 6.5831e-04,
        1.0000e+00, 1.0000e+00, 2.6147e-04, 1.0000e+00]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
179: 0.05856326715445813; roc=0.9974812729936285 test_loss=0.06376836448907852
tensor([1.0000e+00, 9.9994e-01, 3.8122e-05, 2.0562e-03, 1.0000e+00, 7.5876e-04,
        1.0000e+00, 1.0000e+00, 2.5725e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
180: 0.058842810206575155; roc=0.9974890203872616 test_loss=0.06345829367637634
tensor([1.0000e+00, 9.9994e-01, 3.0544e-05, 1.4837e-03, 1.0000e+00, 6.5448e-04,
        1.0000e+00, 1.0000e+00, 2.5379e-04, 9.9999e-01]) tensor([1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])
181: 0.0588883896

tensor([0.9999, 0.9993, 1.0000, 0.0244, 0.9719, 0.0252, 0.9829, 1.0000, 0.9883,
        0.9999]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
11: 0.08710580073756936; roc=0.9961149710037895 test_loss=0.08019138127565384
tensor([0.9999, 0.9994, 1.0000, 0.0162, 0.9716, 0.0086, 0.9957, 1.0000, 0.9949,
        1.0000]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
12: 0.08572484597747708; roc=0.996229308818399 test_loss=0.07806018739938736
tensor([9.9991e-01, 9.9972e-01, 1.0000e+00, 9.6037e-04, 9.9389e-01, 1.8807e-03,
        9.6767e-01, 9.9999e-01, 9.9195e-01, 9.9995e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
13: 0.08406890583259088; roc=0.9963100694635046 test_loss=0.08001552522182465
tensor([0.9999, 0.9998, 1.0000, 0.1737, 0.9868, 0.0244, 0.9712, 1.0000, 0.9937,
        1.0000]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
14: 0.08291291547410282; roc=0.9965162822184553 test_loss=0.07567750662565231
tensor([0.9999, 0.9996, 1.0000, 0.0523, 0.9922, 0.0146, 0.9912, 1

tensor([1.0000, 0.9992, 1.0000, 0.0087, 0.9912, 0.0013, 0.9980, 1.0000, 0.9957,
        0.9997]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
47: 0.06903977562431936; roc=0.9973175251036416 test_loss=0.06622806936502457
tensor([1.0000, 0.9997, 1.0000, 0.0028, 0.9956, 0.0032, 0.9987, 1.0000, 0.9970,
        0.9995]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
48: 0.06857046994530125; roc=0.997278693021771 test_loss=0.06762810051441193
tensor([1.0000, 0.9997, 1.0000, 0.0084, 0.9965, 0.0069, 0.9996, 1.0000, 0.9981,
        0.9999]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
49: 0.06848081983165977; roc=0.9972849427251069 test_loss=0.06856442987918854
tensor([1.0000, 0.9996, 1.0000, 0.0077, 0.9961, 0.0033, 0.9997, 1.0000, 0.9988,
        0.9996]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
50: 0.06815675577631704; roc=0.9972920451391005 test_loss=0.06576791405677795
tensor([0.9999, 0.9997, 1.0000, 0.0071, 0.9964, 0.0032, 0.9997, 1.0000, 0.9984,
        0.9999]) tensor([

tensor([9.9999e-01, 9.9990e-01, 1.0000e+00, 4.0885e-03, 9.9851e-01, 2.4694e-04,
        9.9966e-01, 1.0000e+00, 9.9741e-01, 9.9943e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
82: 0.06401608465078436; roc=0.9974231277627783 test_loss=0.06443645060062408
tensor([9.9999e-01, 9.9953e-01, 1.0000e+00, 4.6745e-03, 9.9558e-01, 6.8113e-04,
        9.9934e-01, 1.0000e+00, 9.9508e-01, 9.9848e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
83: 0.06417559906104464; roc=0.9974483573517635 test_loss=0.06413938105106354
tensor([1.0000, 0.9996, 1.0000, 0.0069, 0.9964, 0.0010, 0.9993, 1.0000, 0.9950,
        0.9984]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
84: 0.06389232095744875; roc=0.9974300872575544 test_loss=0.0639064684510231
tensor([1.0000, 0.9998, 1.0000, 0.0136, 0.9962, 0.0028, 0.9997, 1.0000, 0.9970,
        0.9992]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
85: 0.0638831916966556; roc=0.9974364240546718 test_loss=0.063843734562397
tensor([1.0000, 0.9994, 1.00

tensor([9.9999e-01, 9.9974e-01, 1.0000e+00, 1.0079e-02, 9.9739e-01, 3.9149e-04,
        9.9988e-01, 1.0000e+00, 9.9857e-01, 9.9914e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
114: 0.061932130621539225; roc=0.9975010514537865 test_loss=0.06318732351064682
tensor([1.0000e+00, 9.9959e-01, 1.0000e+00, 4.9882e-03, 9.9525e-01, 4.5968e-04,
        9.9968e-01, 1.0000e+00, 9.9705e-01, 9.9937e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
115: 0.06205341466139128; roc=0.9975088391783941 test_loss=0.06330329179763794
tensor([9.9999e-01, 9.9933e-01, 1.0000e+00, 5.3475e-03, 9.9535e-01, 4.8720e-04,
        9.9964e-01, 1.0000e+00, 9.9744e-01, 9.9901e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
116: 0.062089384507249906; roc=0.9974887255482996 test_loss=0.06368813663721085
tensor([1.0000e+00, 9.9962e-01, 1.0000e+00, 8.4704e-03, 9.9628e-01, 7.2391e-04,
        9.9976e-01, 1.0000e+00, 9.9859e-01, 9.9900e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
117: 0.0619289654

tensor([9.9998e-01, 9.9944e-01, 1.0000e+00, 9.1298e-03, 9.9693e-01, 3.2934e-04,
        9.9979e-01, 1.0000e+00, 9.9641e-01, 9.9841e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
145: 0.06124604285867126; roc=0.9975179314031182 test_loss=0.06281450390815735
tensor([9.9999e-01, 9.9928e-01, 1.0000e+00, 5.7724e-03, 9.9780e-01, 4.0973e-04,
        9.9979e-01, 1.0000e+00, 9.9740e-01, 9.9912e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
146: 0.060902974596362056; roc=0.9975177277775521 test_loss=0.06295081228017807
tensor([9.9999e-01, 9.9918e-01, 1.0000e+00, 7.2644e-03, 9.9731e-01, 5.2723e-04,
        9.9977e-01, 1.0000e+00, 9.9735e-01, 9.9893e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
147: 0.060511720744364055; roc=0.9975136914154842 test_loss=0.06288684904575348
tensor([9.9999e-01, 9.9898e-01, 1.0000e+00, 4.8740e-03, 9.9697e-01, 4.1957e-04,
        9.9969e-01, 1.0000e+00, 9.9699e-01, 9.9905e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
148: 0.0610479506

tensor([9.9999e-01, 9.9915e-01, 1.0000e+00, 8.9079e-03, 9.9767e-01, 3.8264e-04,
        9.9988e-01, 1.0000e+00, 9.9845e-01, 9.9866e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
176: 0.0603177159767092; roc=0.9975181213011183 test_loss=0.06296989321708679
tensor([9.9999e-01, 9.9898e-01, 1.0000e+00, 7.7378e-03, 9.9740e-01, 2.8158e-04,
        9.9987e-01, 1.0000e+00, 9.9802e-01, 9.9848e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
177: 0.060334384985911996; roc=0.9975202733259234 test_loss=0.06297238171100616
tensor([9.9999e-01, 9.9908e-01, 1.0000e+00, 7.9996e-03, 9.9690e-01, 3.5748e-04,
        9.9986e-01, 1.0000e+00, 9.9796e-01, 9.9865e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
178: 0.06013714206071547; roc=0.997511848032127 test_loss=0.06302662938833237
tensor([9.9999e-01, 9.9908e-01, 1.0000e+00, 8.3809e-03, 9.9779e-01, 2.5337e-04,
        9.9983e-01, 1.0000e+00, 9.9768e-01, 9.9885e-01]) tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1.])
179: 0.0605775536615

tensor([9.9985e-01, 1.9198e-02, 1.3260e-02, 1.0000e+00, 5.2747e-07, 8.0589e-04,
        8.5933e-01, 9.9979e-01, 8.3455e-01, 1.4907e-05]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
8: 0.09051013168729381; roc=0.9956573459574872 test_loss=0.09589320421218872
tensor([9.9992e-01, 2.6397e-02, 9.1774e-03, 1.0000e+00, 2.8822e-06, 4.2270e-04,
        9.5493e-01, 9.9989e-01, 9.8918e-01, 1.1855e-04]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
9: 0.08775703649094076; roc=0.9960721681067053 test_loss=0.07959961146116257
tensor([9.9982e-01, 1.0515e-02, 1.3310e-02, 1.0000e+00, 3.1436e-06, 3.8709e-04,
        8.7662e-01, 9.9992e-01, 9.8648e-01, 1.6865e-04]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
10: 0.08563155391150051; roc=0.9961494208006726 test_loss=0.0816047191619873
tensor([9.9988e-01, 3.5699e-02, 7.9613e-03, 1.0000e+00, 2.6918e-06, 5.0761e-04,
        7.8193e-01, 9.9986e-01, 9.7259e-01, 3.2508e-04]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
11: 0.08372749739958917; 

tensor([9.9996e-01, 1.1467e-03, 5.5354e-03, 1.0000e+00, 2.5599e-08, 3.8427e-05,
        9.0537e-01, 9.9995e-01, 9.6278e-01, 7.8152e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
40: 0.0692694087823232; roc=0.9972265434773155 test_loss=0.06713270395994186
tensor([9.9947e-01, 1.3732e-02, 1.8904e-02, 1.0000e+00, 5.6211e-08, 1.4833e-04,
        8.3886e-01, 9.9977e-01, 9.5242e-01, 3.9875e-05]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
41: 0.06859331345852511; roc=0.997233613839234 test_loss=0.06715318560600281
tensor([9.9997e-01, 1.0532e-02, 7.5127e-03, 1.0000e+00, 3.2137e-08, 5.2206e-05,
        9.1394e-01, 9.9999e-01, 9.7720e-01, 1.1839e-05]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
42: 0.06841237482833273; roc=0.9972190911686578 test_loss=0.06822603195905685
tensor([9.9994e-01, 4.7164e-03, 3.6721e-03, 1.0000e+00, 1.7517e-08, 2.6027e-05,
        8.4948e-01, 9.9997e-01, 8.3563e-01, 4.5330e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
43: 0.06834625789044815;

tensor([9.9999e-01, 1.2720e-03, 5.0458e-03, 1.0000e+00, 1.0132e-08, 6.6412e-05,
        9.1501e-01, 9.9999e-01, 9.7183e-01, 6.7642e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
72: 0.0641537238565492; roc=0.9973801955102047 test_loss=0.06554415076971054
tensor([9.9995e-01, 1.0567e-03, 3.0121e-03, 1.0000e+00, 1.5933e-08, 1.0106e-04,
        9.1919e-01, 9.9997e-01, 9.5267e-01, 2.9798e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
73: 0.06385799815073426; roc=0.9973932924394968 test_loss=0.06533251702785492
tensor([9.9995e-01, 2.0642e-03, 2.7026e-03, 1.0000e+00, 2.7750e-09, 4.9659e-05,
        8.2479e-01, 9.9998e-01, 9.1154e-01, 2.9312e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
74: 0.06364293798988248; roc=0.9974051443810545 test_loss=0.06489219516515732
tensor([9.9993e-01, 1.2067e-03, 2.5582e-03, 1.0000e+00, 7.3688e-09, 7.5055e-05,
        8.6459e-01, 9.9998e-01, 9.5451e-01, 4.1440e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
75: 0.06406548473202152

tensor([9.9997e-01, 9.9383e-04, 1.0704e-03, 1.0000e+00, 5.1776e-09, 3.3835e-05,
        8.9331e-01, 9.9999e-01, 9.7672e-01, 3.9515e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
104: 0.06163889072927428; roc=0.9974787554630173 test_loss=0.0638066753745079
tensor([9.9999e-01, 7.4797e-04, 9.3845e-04, 1.0000e+00, 1.7825e-09, 2.5911e-05,
        8.8346e-01, 9.9999e-01, 9.6453e-01, 2.1606e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
105: 0.061805382074765214; roc=0.997477466545306 test_loss=0.06400982290506363
tensor([9.9996e-01, 3.1123e-03, 1.2597e-03, 1.0000e+00, 2.9326e-09, 4.8778e-05,
        9.2150e-01, 9.9999e-01, 9.6685e-01, 2.3313e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
106: 0.06139716428739053; roc=0.997434388474843 test_loss=0.06501296162605286
tensor([9.9998e-01, 2.5161e-03, 1.0887e-03, 1.0000e+00, 4.7686e-09, 6.6986e-05,
        9.2848e-01, 9.9999e-01, 9.8304e-01, 2.7380e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
107: 0.06131282597412

tensor([9.9998e-01, 9.4257e-04, 7.9686e-04, 1.0000e+00, 1.5996e-09, 1.8500e-05,
        9.2502e-01, 9.9999e-01, 9.8589e-01, 1.9332e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
135: 0.06039725273663615; roc=0.9974991920541354 test_loss=0.0635775700211525
tensor([9.9998e-01, 1.2296e-03, 1.0820e-03, 1.0000e+00, 1.0639e-09, 1.4135e-05,
        8.4692e-01, 9.9999e-01, 9.6726e-01, 2.8590e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
136: 0.06023840363010948; roc=0.99746471266642 test_loss=0.06407814472913742
tensor([9.9997e-01, 9.0140e-04, 1.1448e-03, 1.0000e+00, 1.2865e-09, 1.9328e-05,
        8.5719e-01, 9.9999e-01, 9.7212e-01, 1.9363e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
137: 0.060629362103379804; roc=0.9974914428368002 test_loss=0.06375394016504288
tensor([9.9999e-01, 1.9605e-03, 6.0079e-04, 1.0000e+00, 8.5047e-10, 1.7930e-05,
        9.0556e-01, 9.9999e-01, 9.8000e-01, 1.2305e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
138: 0.06035460295132

tensor([9.9998e-01, 1.0170e-03, 5.1312e-04, 1.0000e+00, 8.1614e-10, 3.8247e-05,
        9.0472e-01, 9.9999e-01, 9.8127e-01, 1.4553e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
166: 0.05959027316283297; roc=0.9975057030715274 test_loss=0.06344892084598541
tensor([9.9998e-01, 1.0242e-03, 4.3701e-04, 1.0000e+00, 1.5363e-09, 4.0957e-05,
        8.9094e-01, 9.9999e-01, 9.8102e-01, 2.1087e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
167: 0.06005186209708084; roc=0.9974945977107671 test_loss=0.0635032132267952
tensor([9.9997e-01, 1.4562e-03, 4.7357e-04, 1.0000e+00, 1.5102e-09, 3.8574e-05,
        8.7915e-01, 9.9999e-01, 9.7874e-01, 2.2208e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
168: 0.05981611588118989; roc=0.9974973178610091 test_loss=0.06344354897737503
tensor([9.9997e-01, 8.9414e-04, 7.1458e-04, 1.0000e+00, 1.3779e-09, 3.7698e-05,
        9.0506e-01, 9.9999e-01, 9.7451e-01, 2.2729e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
169: 0.0596897878433

tensor([9.9999e-01, 9.3142e-04, 7.4710e-04, 1.0000e+00, 1.8813e-09, 3.5295e-05,
        8.9989e-01, 9.9999e-01, 9.8164e-01, 2.0657e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
197: 0.059380827376871934; roc=0.9974989845307574 test_loss=0.06346431374549866
tensor([9.9999e-01, 1.0608e-03, 6.2367e-04, 1.0000e+00, 1.2873e-09, 3.0421e-05,
        9.1404e-01, 9.9999e-01, 9.8432e-01, 1.5684e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
198: 0.05980468349140367; roc=0.997508698012924 test_loss=0.06334152817726135
tensor([9.9999e-01, 1.1726e-03, 6.6076e-04, 1.0000e+00, 8.7908e-10, 2.4877e-05,
        9.1369e-01, 9.9999e-01, 9.8524e-01, 1.1368e-06]) tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])
199: 0.05977281501631678; roc=0.997503379358816 test_loss=0.06345333904027939
tensor([5.6914e-04, 1.4305e-01, 1.3275e-02, 3.8910e-01, 9.4877e-04, 1.9061e-03,
        9.9400e-01, 5.0792e-01, 9.9950e-01, 8.9997e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
0: 0.236024240108183

tensor([7.5807e-05, 8.2447e-07, 5.6623e-03, 7.1160e-01, 2.7846e-03, 8.7881e-04,
        9.9979e-01, 8.6956e-01, 9.9709e-01, 9.9991e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
29: 0.07028565620198662; roc=0.9971959144706067 test_loss=0.0673544853925705
tensor([1.1210e-04, 7.4316e-06, 7.6009e-04, 5.5044e-01, 4.6176e-04, 4.1055e-04,
        9.9994e-01, 8.1669e-01, 9.9915e-01, 9.9999e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
30: 0.06974182497388051; roc=0.9972514381644829 test_loss=0.06703603267669678
tensor([3.1309e-04, 4.8292e-07, 4.3861e-03, 6.3253e-01, 3.2742e-03, 2.2678e-03,
        9.9938e-01, 6.4380e-01, 9.9965e-01, 9.9975e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
31: 0.06971594267421298; roc=0.9972056809680094 test_loss=0.06783577799797058
tensor([4.9812e-04, 4.1144e-07, 5.3737e-03, 7.4779e-01, 1.6071e-03, 7.0079e-04,
        9.9995e-01, 7.5916e-01, 9.9952e-01, 9.9987e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
32: 0.06954633753240845

tensor([3.3137e-04, 1.1068e-05, 6.7794e-03, 8.2212e-01, 2.1966e-03, 2.1763e-02,
        9.9988e-01, 8.7059e-01, 9.9992e-01, 9.9983e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
61: 0.06388836925780332; roc=0.9974592944019829 test_loss=0.06538308411836624
tensor([1.1334e-04, 4.0367e-07, 4.5040e-03, 5.4337e-01, 8.7617e-04, 1.8768e-03,
        9.9995e-01, 7.3615e-01, 9.9995e-01, 9.9984e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
62: 0.06330342657588146; roc=0.9974650492562783 test_loss=0.06423264741897583
tensor([7.3679e-05, 6.0750e-06, 3.3983e-03, 7.2829e-01, 3.4712e-04, 1.6299e-03,
        9.9993e-01, 8.9406e-01, 9.9997e-01, 9.9976e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
63: 0.06302928463912305; roc=0.9974643348279639 test_loss=0.0639273151755333
tensor([2.6958e-04, 4.3251e-06, 5.5585e-03, 8.1162e-01, 9.8329e-04, 1.0462e-02,
        9.9999e-01, 8.6045e-01, 9.9994e-01, 9.9989e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
64: 0.0630089260858518;

tensor([6.9856e-05, 3.7917e-06, 4.4134e-03, 6.6821e-01, 3.5539e-04, 2.2249e-03,
        9.9997e-01, 8.6497e-01, 9.9993e-01, 9.9925e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
93: 0.060716319801630794; roc=0.997549146345866 test_loss=0.06281903386116028
tensor([9.7610e-05, 1.1825e-06, 8.6874e-03, 7.3564e-01, 2.6311e-04, 4.0534e-03,
        9.9997e-01, 8.8731e-01, 9.9996e-01, 9.9938e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
94: 0.06053753976100757; roc=0.9975466691831302 test_loss=0.06292284280061722
tensor([1.5483e-04, 6.5208e-07, 4.1030e-03, 6.1039e-01, 1.6023e-04, 1.6359e-03,
        9.9997e-01, 8.4592e-01, 9.9997e-01, 9.9971e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
95: 0.06049763017230564; roc=0.9975620293156294 test_loss=0.06284051388502121
tensor([1.4473e-04, 7.6545e-06, 5.5489e-03, 7.0293e-01, 3.1447e-04, 4.2680e-03,
        9.9992e-01, 8.5214e-01, 9.9994e-01, 9.9962e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
96: 0.0603312394887576

tensor([1.0190e-04, 7.7596e-06, 5.1825e-03, 7.2669e-01, 2.0574e-04, 2.0351e-03,
        9.9996e-01, 9.0185e-01, 9.9999e-01, 9.9974e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
124: 0.05890515970963019; roc=0.997586952781886 test_loss=0.06230543926358223
tensor([1.2218e-04, 3.1540e-06, 6.8304e-03, 6.8141e-01, 1.7082e-04, 2.7159e-03,
        9.9996e-01, 9.0809e-01, 9.9998e-01, 9.9967e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
125: 0.05892089132173562; roc=0.9975738664196896 test_loss=0.062477901577949524
tensor([8.1447e-05, 1.7876e-06, 5.5598e-03, 7.3502e-01, 1.9906e-04, 2.4065e-03,
        9.9997e-01, 9.0543e-01, 9.9998e-01, 9.9975e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
126: 0.05906649897495905; roc=0.9975753656667257 test_loss=0.06249835342168808
tensor([8.3279e-05, 4.4750e-06, 4.8656e-03, 6.9667e-01, 1.6968e-04, 1.4260e-03,
        9.9998e-01, 8.7637e-01, 9.9999e-01, 9.9978e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
127: 0.058545288318

tensor([5.7036e-05, 1.6559e-06, 5.8115e-03, 7.0534e-01, 1.4257e-04, 1.9428e-03,
        9.9997e-01, 9.2430e-01, 9.9998e-01, 9.9951e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
155: 0.05838200270393748; roc=0.9975904989179019 test_loss=0.062411047518253326
tensor([8.6374e-05, 2.0305e-06, 5.5148e-03, 6.0025e-01, 1.3921e-04, 1.7636e-03,
        9.9996e-01, 8.7597e-01, 9.9998e-01, 9.9953e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
156: 0.058503416513587224; roc=0.9975950209105268 test_loss=0.062230877578258514
tensor([6.6796e-05, 3.3989e-06, 4.4661e-03, 6.6819e-01, 1.6617e-04, 1.9355e-03,
        9.9998e-01, 8.7752e-01, 9.9999e-01, 9.9951e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
157: 0.05818524726379065; roc=0.997596459833823 test_loss=0.062260646373033524
tensor([6.0999e-05, 2.4582e-06, 5.1232e-03, 6.6239e-01, 1.0622e-04, 2.1219e-03,
        9.9995e-01, 9.1161e-01, 9.9998e-01, 9.9931e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
158: 0.057947397

tensor([7.8635e-05, 1.6125e-06, 5.0702e-03, 6.4060e-01, 9.8020e-05, 2.2556e-03,
        9.9998e-01, 9.0114e-01, 9.9999e-01, 9.9973e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
186: 0.05771808055815873; roc=0.9975940067700775 test_loss=0.06234874203801155
tensor([5.7666e-05, 2.0667e-06, 5.6100e-03, 6.3582e-01, 1.0242e-04, 2.1890e-03,
        9.9997e-01, 9.0875e-01, 9.9998e-01, 9.9958e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
187: 0.05772979278991252; roc=0.9975915545452214 test_loss=0.06231987848877907
tensor([7.2969e-05, 1.4216e-06, 5.5446e-03, 6.6931e-01, 8.8791e-05, 1.8989e-03,
        9.9997e-01, 8.9995e-01, 9.9999e-01, 9.9971e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
188: 0.05769781435713356; roc=0.9975881526218382 test_loss=0.06242556497454643
tensor([5.9073e-05, 2.3220e-06, 4.6984e-03, 6.5397e-01, 1.2210e-04, 1.7602e-03,
        9.9997e-01, 9.0926e-01, 9.9998e-01, 9.9962e-01]) tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])
189: 0.057955646146

In [67]:
pd_holdout = pd.DataFrame()
pd_holdout['target'] = y_holdout
for isplit in range(5):
    model = MyModel()
    model.load_state_dict(torch.load(f'nn_model_{isplit}.pickle')['model'])
    model.eval()
    with torch.no_grad():
        pd_holdout[f'{isplit}'] = model(torch.Tensor(X_holdout))

In [69]:
pd_holdout['nn_prob'] = pd_holdout[['0','1','2','3','4']].mean(axis=1)
pd_holdout

target             0         1             2             3  \
0           1  9.999733e-01  0.999955  9.996197e-01  9.998216e-01   
1           0  3.482655e-07  0.000002  6.849074e-09  7.695823e-08   
2           1  9.999990e-01  0.999993  9.999303e-01  9.999985e-01   
3           1  9.654357e-01  0.728226  9.791028e-01  9.452514e-01   
4           1  9.996759e-01  0.999997  9.999877e-01  9.998951e-01   
...       ...           ...       ...           ...           ...   
89995       0  3.189360e-03  0.010664  9.675940e-03  1.423564e-02   
89996       1  9.927418e-01  0.999911  9.983478e-01  9.996113e-01   
89997       0  9.094466e-08  0.000002  1.584435e-07  1.880491e-07   
89998       1  3.431977e-02  0.037310  5.278426e-02  4.051618e-02   
89999       1  9.999878e-01  0.999999  9.999986e-01  9.999642e-01   

                  4       nn_prob  
0      9.999269e-01  9.998593e-01  
1      3.159556e-07  5.754856e-07  
2      9.999793e-01  9.999800e-01  
3      7.914397e-01  8.818913e-01  
4      9.999548e-01  9.999021e-01  
...             ...           ...  
89995  2.188519e-02  1.192996e-02  
89996  9.990080e-01  9.979240e-01  
89997  1.264559e-05  2.957890e-06  
89998  9.134308e-02  5.125475e-02  
89999  9.999958e-01  9.999890e-01  

[90000 rows x 7 columns]

In [70]:
tmp = pd.read_csv('xgboost_holdout.csv')
pd_holdout['xgboost_prob'] = tmp['xgboost_prob']
pd_holdout

target             0         1             2             3  \
0           1  9.999733e-01  0.999955  9.996197e-01  9.998216e-01   
1           0  3.482655e-07  0.000002  6.849074e-09  7.695823e-08   
2           1  9.999990e-01  0.999993  9.999303e-01  9.999985e-01   
3           1  9.654357e-01  0.728226  9.791028e-01  9.452514e-01   
4           1  9.996759e-01  0.999997  9.999877e-01  9.998951e-01   
...       ...           ...       ...           ...           ...   
89995       0  3.189360e-03  0.010664  9.675940e-03  1.423564e-02   
89996       1  9.927418e-01  0.999911  9.983478e-01  9.996113e-01   
89997       0  9.094466e-08  0.000002  1.584435e-07  1.880491e-07   
89998       1  3.431977e-02  0.037310  5.278426e-02  4.051618e-02   
89999       1  9.999878e-01  0.999999  9.999986e-01  9.999642e-01   

                  4       nn_prob  xgboost_prob  
0      9.999269e-01  9.998593e-01  9.991639e-01  
1      3.159556e-07  5.754856e-07  6.165386e-12  
2      9.999793e-01  9.999800e-01  9.995431e-01  
3      7.914397e-01  8.818913e-01  8.471072e-01  
4      9.999548e-01  9.999021e-01  9.972556e-01  
...             ...           ...           ...  
89995  2.188519e-02  1.192996e-02  6.157296e-02  
89996  9.990080e-01  9.979240e-01  9.982706e-01  
89997  1.264559e-05  2.957890e-06  5.030987e-06  
89998  9.134308e-02  5.125475e-02  9.341167e-03  
89999  9.999958e-01  9.999890e-01  9.999984e-01  

[90000 rows x 8 columns]

In [72]:
from sklearn.linear_model import LogisticRegression

In [82]:
xt_holdout, yt_holdout = pd_holdout[['nn_prob','xgboost_prob']].values, pd_holdout['target']
for C in [1e-3,1.0,1e+3,1e+6]:
    results = []
    for train_idx, test_idx in kf.split(xt_holdout):
        xtrain, ytrain = xt_holdout[train_idx], yt_holdout[train_idx]
        xtest, ytest = xt_holdout[test_idx], yt_holdout[test_idx]
        clf = LogisticRegression(C=C)
        clf.fit(xtrain, ytrain)
        print(clf.coef_)
        score = roc_auc_score(ytest, clf.predict_proba(xtest)[:,1])
        results.append(score)
    print(f"{C} {np.array(results).mean(),np.array(results).std()}")

[[2.5990119  2.39813972]]
[[2.59502031 2.39739433]]
[[2.59944025 2.39678854]]
[[2.60256142 2.39113569]]
[[2.59455286 2.38878242]]
0.001 (0.9976131446464184, 0.00029577501018954405)
[[7.02735628 2.89444176]]
[[6.93206938 2.94160468]]
[[7.11560864 2.77906583]]
[[7.20743854 2.66179823]]
[[7.04752643 2.69518673]]
1.0 (0.9977848267006294, 0.00028120909497533975)
[[7.14958079 2.80626739]]
[[7.04847029 2.85828375]]
[[7.24659983 2.68165402]]
[[7.34384684 2.55843532]]
[[7.17545548 2.59768665]]
1000.0 (0.9977916509597968, 0.0002800772788277845)
[[7.14970989 2.80617272]]
[[7.04859307 2.8581944 ]]
[[7.24673853 2.68154929]]
[[7.3439914  2.55832419]]
[[7.17559088 2.59758197]]
1000000.0 (0.9977916657837987, 0.0002800647367750917)


In [74]:
clf = LogisticRegression(C=1000)
clf.fit(xt_holdout, yt_holdout)

LogisticRegression(C=1000)

### prepare output

In [76]:
pd_valid = pd.DataFrame()
pd_valid['id'] = valid_series['id']

for isplit in range(5):
    model = MyModel()
    model.load_state_dict(torch.load(f'nn_model_{isplit}.pickle')['model'])
    model.eval()
    with torch.no_grad():
        pd_valid[f'{isplit}'] = model(torch.Tensor(X_valid))

In [77]:
pd_valid['nn_prob'] = pd_valid[['0','1','2','3','4']].mean(axis=1)

In [78]:
tmp = pd.read_csv('xgboost_submit_blend.csv')
pd_valid['xgb_prob'] = tmp['target']
pd_valid

id             0             1             2             3  \
0        900000  9.999933e-01  9.999940e-01  9.999998e-01  9.999931e-01   
1        900001  9.999982e-01  9.999939e-01  9.999727e-01  9.999596e-01   
2        900002  4.686103e-07  1.340410e-09  1.200025e-07  1.667394e-09   
3        900003  2.266349e-06  1.162745e-03  2.503370e-05  9.388438e-06   
4        900004  9.991106e-01  9.981763e-01  9.977717e-01  9.998505e-01   
...         ...           ...           ...           ...           ...   
699995  1599995  6.716827e-01  6.506397e-01  7.472442e-01  7.319505e-01   
699996  1599996  9.999987e-01  9.999599e-01  9.999831e-01  9.999964e-01   
699997  1599997  4.519228e-02  5.872575e-03  8.607415e-02  2.928179e-03   
699998  1599998  1.174141e-05  8.198066e-06  6.891507e-07  3.747346e-05   
699999  1599999  4.762849e-08  2.432071e-10  1.287839e-11  1.578667e-08   

                   4       nn_prob      xgb_prob  
0       9.999944e-01  9.999949e-01  9.999978e-01  
1       9.999901e-01  9.999828e-01  9.997897e-01  
2       2.494749e-08  1.233136e-07  1.963870e-11  
3       3.900878e-05  2.476884e-04  3.375970e-04  
4       9.986734e-01  9.987165e-01  9.992279e-01  
...              ...           ...           ...  
699995  8.485841e-01  7.300202e-01  6.329173e-01  
699996  9.999968e-01  9.999870e-01  9.994021e-01  
699997  2.247222e-02  3.250788e-02  1.275131e-01  
699998  1.518074e-05  1.465657e-05  8.724722e-05  
699999  1.483612e-08  1.570147e-08  1.790670e-15  

[700000 rows x 8 columns]

In [79]:
pd_valid['target'] = clf.predict_proba(pd_valid[['nn_prob','xgb_prob']].values)[:,1]

In [80]:
pd_valid

id             0             1             2             3  \
0        900000  9.999933e-01  9.999940e-01  9.999998e-01  9.999931e-01   
1        900001  9.999982e-01  9.999939e-01  9.999727e-01  9.999596e-01   
2        900002  4.686103e-07  1.340410e-09  1.200025e-07  1.667394e-09   
3        900003  2.266349e-06  1.162745e-03  2.503370e-05  9.388438e-06   
4        900004  9.991106e-01  9.981763e-01  9.977717e-01  9.998505e-01   
...         ...           ...           ...           ...           ...   
699995  1599995  6.716827e-01  6.506397e-01  7.472442e-01  7.319505e-01   
699996  1599996  9.999987e-01  9.999599e-01  9.999831e-01  9.999964e-01   
699997  1599997  4.519228e-02  5.872575e-03  8.607415e-02  2.928179e-03   
699998  1599998  1.174141e-05  8.198066e-06  6.891507e-07  3.747346e-05   
699999  1599999  4.762849e-08  2.432071e-10  1.287839e-11  1.578667e-08   

                   4       nn_prob      xgb_prob    target  
0       9.999944e-01  9.999949e-01  9.999978e-01  0.993705  
1       9.999901e-01  9.999828e-01  9.997897e-01  0.993701  
2       2.494749e-08  1.233136e-07  1.963870e-11  0.007922  
3       3.900878e-05  2.476884e-04  3.375970e-04  0.007943  
4       9.986734e-01  9.987165e-01  9.992279e-01  0.993635  
...              ...           ...           ...       ...  
699995  8.485841e-01  7.300202e-01  6.329173e-01  0.893683  
699996  9.999968e-01  9.999870e-01  9.994021e-01  0.993695  
699997  2.247222e-02  3.250788e-02  1.275131e-01  0.014036  
699998  1.518074e-05  1.465657e-05  8.724722e-05  0.007925  
699999  1.483612e-08  1.570147e-08  1.790670e-15  0.007922  

[700000 rows x 9 columns]

In [81]:
pd_valid[['id','target']].to_csv('stack_submit.csv',index=False)